import { Inter } from "next/font/google";
import "../app/dashboard/assets/css/bootstrap.min.css";
import "../app/dashboard/assets/css/globals.css";
import "../app/dashboard/assets/css/comman.css";
import "../app/dashboard/assets/css/style.css";
import "../app/dashboard/assets/css/responsive.css";
import { ReduxProvider } from "./StoreProvider";
import HeadersTop from "./dashboard/common/HeadersTop";
import { Metadata } from "next";
import SideMenu from "./dashboard/component/SideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ paddingTop: 50 }} className={inter.className}>
        <ReduxProvider>
          
          <HeadersTop />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
